In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../data/raw/Austin_Animal_Center_Outcomes.csv")

In [3]:
df.head()

,Animal ID,Name,DateTime,MonthYear,Date of Birth,Outcome Type,Outcome Subtype,Animal Type,Sex upon Outcome,Age upon Outcome,Breed,Color
0,A882831,*Hamilton,07/01/2023 06:12:00 PM,Jul 2023,03/25/2023,Adoption,NaN,Cat,Neutered Male,3 months,Domestic Shorthair Mix,Black/White
1,A794011,Chunk,05/08/2019 06:20:00 PM,May 2019,05/02/2017,Rto-Adopt,NaN,Cat,Neutered Male,2 years,Domestic Shorthair Mix,Brown Tabby/White
2,A776359,Gizmo,07/18/2018 04:02:00 PM,Jul 2018,07/12/2017,Adoption,NaN,Dog,Neutered Male,1 year,Chihuahua Shorthair Mix,White/Brown
3,A821648,NaN,08/16/2020 11:38:00 AM,Aug 2020,08/16/2019,Euthanasia,NaN,Other,Unknown,1 year,Raccoon,Gray
4,A720371,Moose,02/13/2016 05:59:00 PM,Feb 2016,10/08/2015,Adoption,NaN,Dog,Neutered Male,4 months,Anatol Shepherd/Labrador Retriever,Buff

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 172881 entries, 0 to 172880
Data columns (total 12 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Animal ID         172881 non-null  object
 1   Name              123396 non-null  object
 2   DateTime          172881 non-null  object
 3   MonthYear         172881 non-null  object
 4   Date of Birth     172881 non-null  object
 5   Outcome Type      172837 non-null  object
 6   Outcome Subtype   79214 non-null   object
 7   Animal Type       172881 non-null  object
 8   Sex upon Outcome  172879 non-null  object
 9   Age upon Outcome  172871 non-null  object
 10  Breed             172881 non-null  object
 11  Color             172881 non-null  object
dtypes: object(12)
memory usage: 15.8+ MB

In [5]:
df.isna().sum()

Animal ID               0
Name                49485
DateTime                0
MonthYear               0
Date of Birth           0
Outcome Type           44
Outcome Subtype     93667
Animal Type             0
Sex upon Outcome        2
Age upon Outcome       10
Breed                   0
Color                   0
dtype: int64

In [6]:
X = df[['Age upon Outcome', 'Breed', 'Color', 'Animal Type', 'Sex upon Outcome']]
y = df['Outcome Type']

In [7]:
print("Bağımsız Değişkenler (X):")
display(X.head())

print("\nBağımlı Değişken (y):")
display(y.head())

Bağımsız Değişkenler (X):

,Age upon Outcome,Breed,Color,Animal Type,Sex upon Outcome
0,3 months,Domestic Shorthair Mix,Black/White,Cat,Neutered Male
1,2 years,Domestic Shorthair Mix,Brown Tabby/White,Cat,Neutered Male
2,1 year,Chihuahua Shorthair Mix,White/Brown,Dog,Neutered Male
3,1 year,Raccoon,Gray,Other,Unknown
4,4 months,Anatol Shepherd/Labrador Retriever,Buff,Dog,Neutered Male

Bağımlı Değişken (y):

0      Adoption
1     Rto-Adopt
2      Adoption
3    Euthanasia
4      Adoption
Name: Outcome Type, dtype: object